name: Deploy backend ke hosting

on:
  push:
    branches: [master]
    paths:
      - backend/**
      - .github/workflows/deploy-backend.yml

jobs:
  deploy-backend:
    name: Deploy backend ke hosting
    outputs:
      vendor-changed: ${{ steps.step-check-vendor.outputs.vendor-changed }}
    runs-on: ubuntu-latest

    steps:
      - name: Ambil kode terbaru
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lihat perubahan file
        id: changed-files
        uses: tj-actions/changed-files@v14.5

      - name: Cek apakah composer.lock berubah
        id: step-check-vendor
        if: contains(steps.changed-files.outputs.modified_files, 'composer.lock')
        run: |
          echo "composer.lock telah diubah."
          echo "::set-output name=vendor-changed::true"

      - name: Sinkronisasi file dengan hosting
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_SITE_SERVER}}
          username: ${{ secrets.FTP_SITE_USER}}
          password: ${{ secrets.FTP_SITE_PASS}}
          local-dir: "./backend/"
          server-dir: "truns-api/"
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**

  vendor-check:
    name: Cek composer.lock
    needs: deploy-backend
    if: needs.deploy-backend.outputs.vendor-changed == true
    runs-on: ubuntu-latest

    steps:
      - name: Ambil kode terbaru
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Ambil cache composer jika ada
        id: composer-cache
        working-directory: ./backend
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Menyiapkan php beserta ekstensinya
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.0"
          extensions: openssl, mbstring, pdo_mysql
          tools: composer

      - name: Install dependensi
        working-directory: ./backend
        run: composer install --prefer-dist

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip output
        working-directory: ./backend
        run: zip -qq -r vendor.zip vendor

      - name: Sinkronisasi file dengan hosing
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_SITE_SERVER}}
          username: ${{ secrets.FTP_SITE_USER}}
          password: ${{ secrets.FTP_SITE_PASS}}
          server-dir: "truns-api/"
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**

      - name: Unzip vendor
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL_UNZIP }}

  post-deploy:
    name: Paska deploy
    needs: vendor-check
    runs-on: ubuntu-latest

    steps:
      - name: Migrasi database
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL_MIGRATE }}
