name: Deploy backend ke hosting

on:
  push:
    branches: [master]
    paths:
      - backend/**
      - .github/workflows/deploy-backend.yml

jobs:
  web-deploy:
    name: Deploy backend ke hosting
    runs-on: ubuntu-latest

    steps:
      - name: Ambil kode terbaru
        uses: actions/checkout@v2

      - name: Ambil cache composer jika ada
        id: composer-cache
        working-directory: ./backend
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Menyiapkan php beserta ekstensinya
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.0"
          extensions: openssl, mbstring, pdo_mysql
          tools: composer

      - name: Install dependensi
        working-directory: ./backend
        run: composer install --prefer-dist

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip output
        run: zip -qq -r vendor.zip vendor
        working-directory: ./backend

      - name: Sinkronisasi file dengan hosing
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SITE_SERVER}}
          username: ${{ secrets.FTP_SITE_USER}}
          password: ${{ secrets.FTP_SITE_PASS}}
          local-dir: "./backend/"
          server-dir: "truns-api/"
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            /backend/vendor/**

      - name: Migrasi database
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL_MIGRATE }}
