name: Deploy to hosting

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  web-deploy:
    name: Deploy to hosting
    runs-on: ubuntu-latest

    steps:
      - name: Get the latest code
        uses: actions/checkout@v2

      - uses: actions/setup-node@master
      
      - name: Installing project dependencies
        run: npm install
        
      - name: Building the project
        run: npm run generate
        
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SITE_SERVER}}
          username: ${{ secrets.FTP_SITE_USER}}
          password: ${{ secrets.FTP_SITE_PASS}}
          local-dir: "./dist/"
          dangerous-clean-slate: true
